### ISSUE TITLE
Retard Rasmus har kod som slår med fel hand

### ISSUE THREAD

**Issue by ineentho** [ineentho/textspel#29]
```
Nov 02 00:15:50 narnia2 npm[4910]: false
Nov 02 00:15:50 narnia2 npm[4910]: Fight 58192224800d1613469dc0d5 stored successfully.
Nov 02 00:15:50 narnia2 npm[4910]: 1597, 1403
Nov 02 00:15:50 narnia2 npm[4910]: Updated rank for stenfiskeN.
Nov 02 00:15:50 narnia2 npm[4910]: Updated rank for Ineentho.
Nov 02 00:16:31 narnia2 npm[4910]: New fight created: 5819224f800d1613469dc0d6
Nov 02 00:16:34 narnia2 npm[4910]: No current weapon 1 Fight {
Nov 02 00:16:34 narnia2 npm[4910]:   modifierStorage:
Nov 02 00:16:34 narnia2 npm[4910]:    { dodge: { dodged: false, remainingAttacks: 0 },
Nov 02 00:16:34 narnia2 npm[4910]:      timestop: { hasTimeStopped: true } },
Nov 02 00:16:34 narnia2 npm[4910]:   playerStates:
Nov 02 00:16:34 narnia2 npm[4910]:    [ { currentHP: 128, maxHP: 146, player: [Object], buffs: [Object] },
Nov 02 00:16:34 narnia2 npm[4910]:      { currentHP: 75, maxHP: 81, player: [Object], buffs: [] } ],
Nov 02 00:16:34 narnia2 npm[4910]:   turn: 1,
Nov 02 00:16:34 narnia2 npm[4910]:   currentWeapon: 1,
Nov 02 00:16:34 narnia2 npm[4910]:   numAttacks: -0.24,
Nov 02 00:16:34 narnia2 npm[4910]:   attackId: 7,
Nov 02 00:16:34 narnia2 npm[4910]:   buffRound: false,
Nov 02 00:16:34 narnia2 npm[4910]:   textData: {},
Nov 02 00:16:34 narnia2 npm[4910]:   attackerNum: 1,
Nov 02 00:16:34 narnia2 npm[4910]:   defenderNum: 0,
Nov 02 00:16:34 narnia2 npm[4910]:   attacker:
Nov 02 00:16:34 narnia2 npm[4910]:    { currentHP: 75,
Nov 02 00:16:34 narnia2 npm[4910]:      maxHP: 81,
Nov 02 00:16:34 narnia2 npm[4910]:      player:
Nov 02 00:16:34 narnia2 npm[4910]:       ServerPlayer {
Nov 02 00:16:34 narnia2 npm[4910]:         inventory: [Object],
Nov 02 00:16:34 narnia2 npm[4910]:         equipped: [Object],
Nov 02 00:16:34 narnia2 npm[4910]:         reassemble: [Object],
Nov 02 00:16:34 narnia2 npm[4910]:         id: 579e4f1802d1e75f4235093f,
Nov 02 00:16:34 narnia2 npm[4910]:         key: undefined,
Nov 02 00:16:34 narnia2 npm[4910]:         ServerPlayer: true },
Nov 02 00:16:34 narnia2 npm[4910]:      buffs: [] },
Nov 02 00:16:34 narnia2 npm[4910]:   defender:
Nov 02 00:16:34 narnia2 npm[4910]:    { currentHP: 128,
Nov 02 00:16:34 narnia2 npm[4910]:      maxHP: 146,
Nov 02 00:16:34 narnia2 npm[4910]:      player:
Nov 02 00:16:34 narnia2 npm[4910]:       ServerPlayer {
Nov 02 00:16:34 narnia2 npm[4910]:         inventory: [Object],
Nov 02 00:16:34 narnia2 npm[4910]:         equipped: [Object],
Nov 02 00:16:34 narnia2 npm[4910]:         reassemble: [Object],
Nov 02 00:16:34 narnia2 npm[4910]:         id: 57b56d27d0e1c25a594e729a,
Nov 02 00:16:34 narnia2 npm[4910]:         key: undefined,
Nov 02 00:16:34 narnia2 npm[4910]:         ServerPlayer: true },
Nov 02 00:16:34 narnia2 npm[4910]:      buffs: [ [Object] ] },
Nov 02 00:16:34 narnia2 npm[4910]:   weapons: [ { stats: [Object], weapon: [Object], slot: 4 } ],
Nov 02 00:16:34 narnia2 npm[4910]:   damage: 4,
Nov 02 00:16:34 narnia2 npm[4910]:   hasWeapon: true,
Nov 02 00:16:34 narnia2 npm[4910]:   miss: false,
Nov 02 00:16:34 narnia2 npm[4910]:   attackerIndex: 0,
Nov 02 00:16:34 narnia2 npm[4910]:   defenderIndex: 1 }
Nov 02 00:16:34 narnia2 npm[4910]: err  TypeError: Cannot read property 'stats' of undefined
Nov 02 00:16:34 narnia2 npm[4910]:     at Fight.initAttack (file:///home/ineentho/textspel/game/server//fight.js!transpiled:105:48)
Nov 02 00:16:34 narnia2 npm[4910]:     at Fight.attack (file:///home/ineentho/textspel/game/server//fight.js!transpiled:75:20)
Nov 02 00:16:34 narnia2 npm[4910]:     at FightManager.attack (file:///home/ineentho/textspel/game/server//fightManager.js!transpiled:176:39)
Nov 02 00:16:34 narnia2 npm[4910]:     at Timeout._onTimeout (file:///home/ineentho/textspel/game/server//fightManager.js!transpiled:191:30)
Nov 02 00:16:34 narnia2 npm[4910]:     at ontimeout (timers.js:365:14)
Nov 02 00:16:34 narnia2 npm[4910]:     at tryOnTimeout (timers.js:237:5)
Nov 02 00:16:34 narnia2 npm[4910]:     at Timer.listOnTimeout (timers.js:207:5)
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! Linux 4.6.4-1-ARCH
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "run"
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! node v6.8.1
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! npm  v3.10.8
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! code ELIFECYCLE
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! retardarenan@1.0.0 run: `jspm run app.js --production`
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! Exit status 1
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR!
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! Failed at the retardarenan@1.0.0 run script 'jspm run app.js --production'.
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! Make sure you have the latest version of node.js and npm installed.
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! If you do, this is most likely a problem with the retardarenan package,
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! not with npm itself.
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! Tell the author that this fails on your system:
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR!     jspm run app.js --production
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! You can get information on how to open an issue for this project with:
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR!     npm bugs retardarenan
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! Or if that isn't available, you can get their info via:
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR!     npm owner ls retardarenan
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! There is likely additional logging output above.
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR! Please include the following file with any support request:
Nov 02 00:16:34 narnia2 npm[4910]: npm ERR!     /home/ineentho/textspel/game/npm-debug.log

```

Samma issue som vanligt, @MonsterPenguin blamar multistriken

**Comment by Kofotsmordarn** [comment]
Nej men undrar om jag visste detta och sa från hela början att jag skulle göra något åt det??Tycker du det e dags att jag börjar??

**Comment by Kofoten** [comment]
@ineentho Jag väljer inte ens hand!

**Comment by Kofoten** [comment]
lämnar issue öppen ifall någon ogillar min lösning...  @ineentho

**Comment by Kofoten** [comment]
Det var en nolla på fel ställe.
